# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
#before_all do
#  update_fastlane
    ANDROID_VERSION_NAME = android_get_version_name()
#end

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build debug|dev|staging|release version"
  lane :build do |options|
    env = options[:env]
    if env then
      build_type = env.capitalize
    else
      puts "Choosing Debug as the default build type."
      build_type = 'Debug'
    end

    if env == 'dev' or env == 'staging' then
      build_num = ENV["CIRCLE_BUILD_NUM"] ? ENV["CIRCLE_BUILD_NUM"] : 'local'
      add_badge(
        shield: "#{ANDROID_VERSION_NAME}-#{build_num}-orange",
        glob: "/app/src/main/res/mipmap-*/*.{png,PNG}",
        no_badge: true
      )
    end

    build_number = number_of_commits()
    gradle(
     <%if (props.useAabBuilds) { -%> task: 'bundle',
     <% } else { -%> task: 'assemble',
     <% } -%> build_type: build_type,
      properties: {
        "VERSION_CODE" => build_number
      }
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Build and push to Google Play"
  lane :build_deploy do |options|
    env = options[:env]
    build(env: env)
    deploy(env: env)
  end

  desc "Push to Google Play"
  lane :deploy do |options|
    env = options[:env]
    if env != 'dev' and env != 'staging' and env != 'release' then
      raise 'env must be one of dev|staging|release'
    end
    package_name_postfix = {
      'release' => '',
      'dev' => '.dev',
      'staging' => '.staging'
    }[env]
    upload_to_play_store(
      package_name:  "<%= props.appId %>#{package_name_postfix}",
      track: 'internal',
     <% if (props.useAabBuilds) { -%> aab: "./app/build/outputs/bundle/#{env}/app.aab"-%>
     <% } else { -%> apk: "./app/build/outputs/apk/#{env}/release/app-#{env}-release.apk"-%>
     <% } %>
    )
  end
end
